"""
generate_counterfactual_cot.py — Offline counterfactual (reasoning, trajectory)
pair generation for the AutoVLA contrastive/cycle-consistency pilot.

For each nuScenes trainval scene, this produces a K-way group:
  - 1 "real" pair: reasoning text generated by Qwen2.5-VL-72B-Instruct given the
    scene's TRUE ego meta-action as a hint (same prompt/technique AutoVLA's own
    nuPlan/Waymo preprocessing already uses, see cot_prompts.get_cot_reasoning_prompt),
    paired with the scene's actual ground-truth trajectory.
  - K-1 "counterfactual" pairs: reasoning text generated the same way but hinted
    with a plausible ALTERNATIVE meta-action (different lateral/longitudinal
    combo than GT), paired with a trajectory obtained by teacher-forcing that
    counterfactual reasoning text into the existing trained AutoVLA SFT
    checkpoint and letting it continue into action tokens (reuses
    tools/ablation/cot_ablation.py's continue_from_text).

Why nuScenes rather than nuPlan/navtest for this pilot: nuPlan trainval raw
data isn't available locally, and navtest is a held-out eval split (training on
it would be test-set contamination). nuScenes trainval raw data IS available
locally and is already one of AutoVLA's own SFT training sources.

Why regenerate the "real" CoT too instead of reusing nuScenes' existing
DriveLM-templated CoT: nuScenes' native CoT (tools/preprocessing/
nusc_sample_generation.py's process_drivelm_data) is template-assembled from
QA annotations, not VLM-generated -- pairing that style of text against
VLM-narrative-style counterfactual text would let the contrastive/cycle loss
trivially separate "real" from "counterfactual" by writing style rather than
content. Generating every pair in a K-group through the identical VLM
pipeline keeps that confound out.

This script only produces data -- it does not train anything. Output: one
augmented JSON per scene (additive to the schema nusc_sample_generation.py
already produces), written under --output_dir.

Usage (single process, on a box with the real NFS mount, e.g. grizzly):
    python tools/preprocessing/generate_counterfactual_cot.py \
        --nuscenes_path /media/training_data/nuscenes/nuscenes \
        --sft_config config/training/qwen2.5-vl-3B-nuplan-navtest-eval.yaml \
        --output_dir /media/training_data/<user>/autovla_contrastive_pilot/nuscenes_train \
        --num_scenes 300 --k_counterfactuals 4

Usage (no NFS mount, e.g. a Lilypad cluster node -- see autovla_lilypad/run.py
for the real entrypoint that does this): point --nuscenes_path at an empty
local directory and --sft_checkpoint_override at a locally-downloaded
checkpoint; metadata tables + touched camera images are pulled from
s3://research-datasets-chicago/nuscenes/ on demand, and --vlm_model_path's
default (a HF repo id) auto-downloads via HF_TOKEN.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "navsim"))

import numpy as np
import torch
import yaml
from nuscenes.nuscenes import NuScenes
from nuscenes.utils import splits
from qwen_vl_utils import process_vision_info
from transformers import AutoProcessor

from tools.preprocessing.nusc_sample_generation import (
    get_ego_pose_future_his,
    get_ego_velocity,
    get_planning_instruction,
)
from dataset_utils.preprocessing.cot_annotation_model import CoTAnnotationModel
from dataset_utils.preprocessing.cot_prompts import get_cot_reasoning_prompt
from models.autovla import SFTAutoVLA
from tools.ablation.cot_ablation import continue_from_text, _to_device

logger = logging.getLogger(__name__)

# Only the 3 cameras build_cot_generation_inputs/build_input_features actually
# use (matching AutoVLA.get_prompt's own 3-camera framing) -- fetching the
# other 3 would just be wasted S3 bandwidth on a cluster node.
CAMERA_TYPES = ["CAM_FRONT", "CAM_FRONT_RIGHT", "CAM_FRONT_LEFT"]
HIS_TS = 3
FUT_TS = 16

LATERAL_OPTIONS = ["move forward", "turn left", "change lane to left", "turn right", "change lane to right"]
LONGITUDINAL_OPTIONS = ["stop", "a deceleration to zero", "a constant speed",
                         "a quick deceleration", "a deceleration", "a quick acceleration", "an acceleration"]
_LATERAL_FLIP = {
    "move forward": "turn left",
    "turn left": "turn right",
    "change lane to left": "change lane to right",
    "turn right": "turn left",
    "change lane to right": "change lane to left",
}
_LONGITUDINAL_FLIP = {
    "stop": "an acceleration",
    "a deceleration to zero": "an acceleration",
    "a constant speed": "a quick deceleration",
    "a quick deceleration": "a quick acceleration",
    "a deceleration": "an acceleration",
    "a quick acceleration": "a quick deceleration",
    "an acceleration": "a deceleration",
}
_LONGITUDINAL_ADJACENT = {
    "stop": "a deceleration to zero",
    "a deceleration to zero": "a deceleration",
    "a constant speed": "a deceleration",
    "a quick deceleration": "a deceleration",
    "a deceleration": "a constant speed",
    "a quick acceleration": "a constant speed",
    "an acceleration": "a constant speed",
}


def parse_gt_hint(meta_action: str) -> Tuple[str, str]:
    """Split get_planning_instruction()'s output into (lateral, longitudinal).
    "stop" scenes have no lateral component -- treated as ("move forward", "stop")
    purely so the swap logic below has something to flip."""
    text = meta_action.strip().lower().rstrip("\n")
    if text == "stop":
        return "move forward", "stop"
    if " with " not in text:
        raise ValueError(f"Unrecognized meta-action format: {meta_action!r}")
    lateral, longitudinal = text.split(" with ", 1)
    return lateral.strip(), longitudinal.strip()


def build_alternative_hints(gt_lateral: str, gt_longitudinal: str, k: int) -> List[str]:
    """Curated (not random) alternative action hints, ordered from most to
    least different from GT: opposite lateral+longitudinal, opposite lateral
    only, opposite longitudinal only, then a "moderately different" adjacent
    longitudinal bucket. Truncated/cycled to exactly k entries."""
    alt_lateral = _LATERAL_FLIP[gt_lateral]
    alt_longitudinal = _LONGITUDINAL_FLIP[gt_longitudinal]
    adjacent_longitudinal = _LONGITUDINAL_ADJACENT[gt_longitudinal]

    candidates = [
        f"{alt_lateral} with {alt_longitudinal}",
        f"{alt_lateral} with {gt_longitudinal}",
        f"{gt_lateral} with {alt_longitudinal}",
        f"{gt_lateral} with {adjacent_longitudinal}",
    ]
    # De-dupe against the true GT hint and against each other, then cycle to fill k.
    gt_hint = f"{gt_lateral} with {gt_longitudinal}"
    seen = {gt_hint}
    unique = []
    for c in candidates:
        if c not in seen:
            unique.append(c)
            seen.add(c)
    while len(unique) < k:
        unique.append(unique[len(unique) % max(len(unique), 1)])
    return unique[:k]


def _s3_client():
    import boto3
    from botocore.config import Config

    return boto3.client(
        "s3",
        endpoint_url=os.environ.get("AWS_ENDPOINT_URL_S3"),
        config=Config(
            signature_version="s3v4",
            request_checksum_calculation="when_required",
            response_checksum_validation="when_required",
            s3={"payload_signing_enabled": True},
            retries={"max_attempts": 5, "mode": "adaptive"},
        ),
    )


def ensure_local(path: str, dataroot: str, s3_bucket: str, s3_prefix: str) -> str:
    """Lazily download a file from s3://s3_bucket/s3_prefix/<path relative to
    dataroot> if it isn't already present locally. On grizzly (where
    /media/training_data/nuscenes/nuscenes is a real NFS mount) this is a
    no-op every time; on a Lilypad cluster node -- which does not have that
    mount -- it downloads just the files actually touched, instead of staging
    the full ~300GB+ nuScenes samples/ directory."""
    if os.path.exists(path):
        return path
    rel = os.path.relpath(path, dataroot)
    key = f"{s3_prefix.rstrip('/')}/{rel}"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    _s3_client().download_file(s3_bucket, key, path)
    return path


# NuScenes.__init__ (nuscenes/nuscenes.py) auto-loads lidar segmentation
# label files whenever lidarseg.json/panoptic.json are present and non-empty
# in the metadata dir -- it then expects a SEPARATE lidarseg/<version>/ and
# panoptic/<version>/ directory tree of .bin label files, which we don't
# fetch (irrelevant to trajectory/camera-based generation) and don't want to
# (huge). Confirmed via a real cluster run's
# "FileNotFoundError: .../nuscenes/lidarseg/v1.0-trainval". Excluding these
# two files from the sync keeps that code path from ever triggering.
# image_annotations.json (~1.1GB) is also conditionally auto-loaded
# (nuscenes.py:113-115) but never read by anything in this script (we only
# use nusc.sample/scene/ego_pose/sample_data) -- skipped purely to avoid a
# multi-minute JSON parse x 4 parallel worker processes for nothing.
_METADATA_FILES_TO_SKIP = {"lidarseg.json", "panoptic.json", "image_annotations.json"}

# Exactly the JSON tables NuScenes.__init__ loads for a plain (no lidarseg/
# panoptic) index build -- what "the metadata is complete" actually means.
# "Directory exists and is non-empty" is NOT a completeness check: the job is
# preemptible with requeue, and a mid-sync preemption leaves a partial dir
# that a non-emptiness check would then treat as done forever after (the
# autovla-counterfactual-pilot-hf979a failure mode, one directory-layout bug
# removed).
_REQUIRED_METADATA_TABLES = (
    "category", "attribute", "visibility", "instance", "sensor",
    "calibrated_sensor", "ego_pose", "log", "scene", "sample",
    "sample_data", "sample_annotation", "map",
)


def _sync_s3_prefix(local_dir: str, s3_bucket: str, s3_key_prefix: str, skip_basenames=frozenset()) -> int:
    """Download every object under s3://s3_bucket/s3_key_prefix/ into
    local_dir, mirroring the S3 key structure relative to s3_key_prefix (i.e.
    local_dir IS the local mirror root of that prefix, not some ancestor of it).
    Idempotent per file: anything already present with the listed size is kept
    (boto3's download_file writes to a temp name and renames on completion, so
    a file existing at its final path with the right size means it finished),
    letting a requeued run resume a preempted sync instead of redoing it."""
    os.makedirs(local_dir, exist_ok=True)
    s3 = _s3_client()
    prefix = f"{s3_key_prefix.rstrip('/')}/"
    paginator = s3.get_paginator("list_objects_v2")
    n = 0
    for page in paginator.paginate(Bucket=s3_bucket, Prefix=prefix):
        for obj in page.get("Contents", []):
            if os.path.basename(obj["Key"]) in skip_basenames:
                continue
            key = obj["Key"]
            local_path = os.path.join(local_dir, key[len(prefix):])
            if os.path.exists(local_path) and os.path.getsize(local_path) == obj["Size"]:
                continue
            os.makedirs(os.path.dirname(local_path), exist_ok=True)
            s3.download_file(s3_bucket, key, local_path)
            n += 1
    return n


def _purge_unservable_label_tables(dataroot: str, version: str) -> None:
    """Delete stale lidarseg.json/panoptic.json left in a rank workdir by a
    sync from before _METADATA_FILES_TO_SKIP existed: their presence makes
    NuScenes.__init__ auto-load those tables and then crash on the missing
    lidarseg/<version>/ (resp. panoptic/<version>/) label directories -- the
    original FileNotFoundError the skip list was added for, which stale node
    state would otherwise resurrect forever. Guarded by the label dir being
    absent, so on grizzly's NFS mount (which has real lidarseg/ and panoptic/
    label trees, verified) this never touches anything."""
    for table in ("lidarseg", "panoptic"):
        table_json = os.path.join(dataroot, version, f"{table}.json")
        if os.path.exists(table_json) and not os.path.isdir(os.path.join(dataroot, table, version)):
            os.remove(table_json)
            logger.info("Removed stale %s (no %s/%s label dir to serve it)", table_json, table, version)


def ensure_metadata_tables(dataroot: str, version: str, s3_bucket: str, s3_prefix: str) -> None:
    """Download the (few-GB) v1.0-trainval metadata JSON tables NuScenes()
    needs to build its index, unless every required table is already present
    locally (true on grizzly's NFS mount, which must never be written to --
    the all-present early return is what keeps this a no-op there)."""
    local_version_dir = os.path.join(dataroot, version)
    _purge_unservable_label_tables(dataroot, version)
    if all(os.path.exists(os.path.join(local_version_dir, f"{t}.json")) for t in _REQUIRED_METADATA_TABLES):
        return
    n = _sync_s3_prefix(
        local_version_dir, s3_bucket, f"{s3_prefix.rstrip('/')}/{version}",
        skip_basenames=_METADATA_FILES_TO_SKIP,
    )
    logger.info("Downloaded %d metadata files from s3://%s/%s/%s to %s", n, s3_bucket, s3_prefix, version, local_version_dir)


def ensure_maps(dataroot: str, version: str, s3_bucket: str, s3_prefix: str) -> None:
    """Download nuScenes' maps/ directory (small, ~500MB total) --
    NuScenes.__init__ EAGERLY initializes a MapMask object per map record
    (nuscenes.py:117, not lazy like lidarseg/panoptic), asserting each map's
    PNG mask file exists on disk. Confirmed via a real cluster run's
    "AssertionError: map mask .../maps/<hash>.png does not exist".
    Completeness = every mask file map.json references exists (map.json is in
    the metadata dir, which ensure_metadata_tables has already ensured) --
    same partial-dir rationale as _REQUIRED_METADATA_TABLES."""
    with open(os.path.join(dataroot, version, "map.json")) as f:
        mask_files = [record["filename"] for record in json.load(f)]
    if all(os.path.exists(os.path.join(dataroot, rel)) for rel in mask_files):
        return
    n = _sync_s3_prefix(os.path.join(dataroot, "maps"), s3_bucket, f"{s3_prefix.rstrip('/')}/maps")
    logger.info("Downloaded %d map files from s3://%s/%s/maps to %s", n, s3_bucket, s3_prefix, os.path.join(dataroot, "maps"))


def load_scene_geometry(
    nusc: NuScenes, sample: dict, dataroot: str, s3_bucket: str, s3_image_prefix: str,
) -> Dict[str, Any] | None:
    if sample["prev"] == "":
        return None
    result = get_ego_pose_future_his(nusc, FUT_TS, sample, HIS_TS)
    fut_diff, fut_trajs, his_trajs, his_diff, fut_masks, his_masks, command = result
    if np.sum(fut_masks) < 10 or np.sum(his_masks) < 3:
        return None

    ego_v = get_ego_velocity(sample, nusc)
    sample_prev = nusc.get("sample", sample["prev"])
    ego_v_prev = get_ego_velocity(sample_prev, nusc)
    ego_acc = (ego_v - ego_v_prev) / 0.5

    gt_meta_action = get_planning_instruction(fut_diff, fut_trajs, his_diff, his_trajs)

    fut_trajs_out = fut_trajs[:11]
    fut_trajs_f = np.zeros((fut_trajs_out.shape[0], 3))
    fut_trajs_f[:, 0] = fut_trajs_out[:, 1]
    fut_trajs_f[:, 1] = -fut_trajs_out[:, 0]
    heading = np.arctan2(
        fut_trajs_f[1:, 1] - fut_trajs_f[:-1, 1],
        fut_trajs_f[1:, 0] - fut_trajs_f[:-1, 0] + 1e-3,
    )
    fut_trajs_f[1:, 2] = heading

    camera_paths: Dict[str, List[str]] = {}
    for cam in CAMERA_TYPES:
        key = cam.lower().replace("cam_", "")
        camera_paths[f"{key}_camera_paths"] = []
    sample_cur = sample
    for i in range(HIS_TS, -1, -1):
        if sample_cur is None:
            return None
        for cam in CAMERA_TYPES:
            key = cam.lower().replace("cam_", "")
            cam_path, _, _ = nusc.get_sample_data(sample_cur["data"][cam])
            cam_path = ensure_local(cam_path, dataroot, s3_bucket, s3_image_prefix)
            camera_paths[f"{key}_camera_paths"].insert(0, cam_path)
        if i != 0:
            sample_cur = nusc.get("sample", sample_cur["prev"]) if sample_cur["prev"] else None

    return {
        "token": sample["token"],
        "gt_trajectory": fut_trajs_f[1:].tolist(),
        "instruction": command,
        "velocity": float(ego_v),
        "acceleration": float(ego_acc),
        "gt_meta_action": gt_meta_action,
        **camera_paths,
    }


def build_cot_generation_inputs(processor: AutoProcessor, scene: dict, hint: str) -> dict:
    """Same 3-camera (front/front_left/front_right) framing AutoVLA's own
    AutoVLA.get_prompt (models/autovla.py) uses at train/inference time, so the
    visual context matches what continue_from_text will later condition on --
    NOT nuplan_dataset.py's 4-camera (front/back/left/right) CoT-labeling
    framing, which only exists for building training targets and is never seen
    by the model itself."""
    min_pixels = 109760
    max_pixels = 109760
    front = [f"file://{p}" for p in scene["front_camera_paths"]]
    front_left = [f"file://{p}" for p in scene["front_left_camera_paths"]]
    front_right = [f"file://{p}" for p in scene["front_right_camera_paths"]]

    messages = [
        {"role": "system", "content": "As a professional driver, how do you drive in the following scenario."},
        {
            "role": "user",
            "content": [
                {"type": "text", "text": (
                    "Three cameras are mounted on the vehicle: front, front-left, and front-right. "
                    "Each video below shows four sequential frames sampled at 2 Hz."
                )},
                {"type": "text", "text": "The video is from the front camera."},
                {"type": "video", "min_pixels": min_pixels, "max_pixels": max_pixels, "video": front},
                {"type": "text", "text": "The video is from the front-left camera."},
                {"type": "video", "min_pixels": min_pixels, "max_pixels": max_pixels, "video": front_left},
                {"type": "text", "text": "The video is from the front-right camera."},
                {"type": "video", "min_pixels": min_pixels, "max_pixels": max_pixels, "video": front_right},
                {"type": "text", "text": (
                    f"The ego vehicle's current velocity is {scene['velocity']:.3f} m/s and current "
                    f"acceleration is {scene['acceleration']:.3f} m/s^2. "
                    f"The current driving command instruction is: {scene['instruction']}."
                )},
                get_cot_reasoning_prompt(hint),
            ],
        },
    ]
    image_inputs, video_inputs = process_vision_info(messages)
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True, add_vision_id=True)
    return {"text": text, "image_inputs": image_inputs, "video_inputs": video_inputs}


def build_input_features(scene: dict) -> dict:
    """Matches the shape AutoVLA.get_prompt (models/autovla.py) expects --
    its own comment anticipates exactly this nuScenes case ("nuScenes stores
    full paths, use them as-is")."""
    return {
        "images": {
            "front_camera": scene["front_camera_paths"],
            "front_left_camera": scene["front_left_camera_paths"],
            "front_right_camera": scene["front_right_camera_paths"],
        },
        "sensor_data_path": "",
        "vehicle_velocity": scene["velocity"],
        "vehicle_acceleration": scene["acceleration"],
        "driving_command": scene["instruction"],
    }


def load_sft_model(
    config_path: str, device: str, checkpoint_override: str | None = None,
) -> Tuple[SFTAutoVLA, AutoProcessor]:
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
    processor = AutoProcessor.from_pretrained(config["model"]["pretrained_model_path"], use_fast=True)
    model = SFTAutoVLA(config)
    model.autovla.vlm.resize_token_embeddings(len(processor.tokenizer))
    checkpoint_path = checkpoint_override or config["model"]["sft_model_path"]
    # map_location must be CPU: the model is still CPU-resident here, and on a
    # cluster worker cuda:0 already holds its half of the 72B labeler --
    # materializing this 16GB fp32 checkpoint there OOMs deterministically.
    state_dict = torch.load(Path(checkpoint_path), map_location="cpu")["state_dict"]
    model.autovla.load_state_dict(state_dict, strict=False)
    del state_dict
    model.to(device)
    model.autovla.device = device
    model.eval()
    return model, processor


def _scene_owner(token: str, world_size: int) -> int:
    """Stable sample->rank assignment (same md5-based approach as
    counterfactual/run.py's _scene_owner) so resume/requeue always maps a
    sample to the same rank -- builtin hash() is per-process randomized and
    would break that guarantee across worker processes."""
    digest = hashlib.md5(token.encode()).hexdigest()
    return int(digest, 16) % world_size


def iter_pilot_scenes(
    nusc: NuScenes, num_scenes: int, rank: int, world_size: int,
    dataroot: str, s3_bucket: str, s3_image_prefix: str,
):
    train_scene_names = set(splits.train)
    available = {s["name"]: s["token"] for s in nusc.scene}
    train_scene_tokens = {available[n] for n in train_scene_names if n in available}

    # One K-group per SCENE (the first qualifying sample of each), sharded by
    # scene token -- not one per sample. nusc.sample is scene-grouped, so
    # per-sample iteration capped at num_scenes yields consecutive 0.5s-apart
    # keyframes from only the first ~num_scenes/40 scenes: near-duplicate
    # K-groups sharing 3 of 4 history frames, ~30x less scene diversity than
    # the count suggests -- exactly the style/content confound this pilot's
    # docstring is at pains to avoid.
    yielded = 0
    done_scenes: set = set()
    for sample in nusc.sample:
        scene_token = sample["scene_token"]
        if scene_token not in train_scene_tokens or scene_token in done_scenes:
            continue
        if _scene_owner(scene_token, world_size) != rank:
            continue
        geometry = load_scene_geometry(nusc, sample, dataroot, s3_bucket, s3_image_prefix)
        if geometry is None:
            continue
        done_scenes.add(scene_token)
        yield geometry
        yielded += 1
        if yielded >= num_scenes:
            return


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nuscenes_path", type=str, default="/media/training_data/nuscenes/nuscenes")
    parser.add_argument("--nuscenes_version", type=str, default="v1.0-trainval")
    # research-datasets-chicago/nuscenes/ mirrors the exact NuScenes devkit
    # layout (v1.0-trainval/ metadata tables + samples/CAM_*/ images) --
    # confirmed present via `aws s3 ls`. Used as a fallback source for
    # whatever isn't already present under --nuscenes_path (real on grizzly's
    # NFS mount; absent on a Lilypad cluster node, which has no such mount).
    parser.add_argument("--nuscenes_s3_bucket", type=str, default="research-datasets-chicago")
    parser.add_argument("--nuscenes_s3_prefix", type=str, default="nuscenes")
    # HF repo ids by default (auto-download via from_pretrained/HF_TOKEN) --
    # neither Qwen model nor the AutoVLA checkpoint were found on S3 (checked
    # research-datasets-chicago's hf_downloads/, models/huggingface/,
    # model_checkpoints/*/huggingface/); they're public/HF-hosted already
    # (Qwen/Qwen2.5-VL-72B-Instruct, and Zewei-Zhou/AutoVLA's
    # AutoVLA_PDMS_89.ckpt per the AutoVLA README's checkpoint-release note).
    parser.add_argument("--vlm_model_path", type=str, default="Qwen/Qwen2.5-VL-72B-Instruct")
    parser.add_argument("--sft_config", type=str, default="config/training/qwen2.5-vl-3B-nuplan-navtest-eval.yaml")
    parser.add_argument("--sft_checkpoint_override", type=str, default=None,
                         help="Local path to override sft_config's model.sft_model_path (e.g. after "
                              "downloading it from HF hub) instead of editing the config file per-run.")
    parser.add_argument("--output_dir", type=str, required=True)
    parser.add_argument("--num_scenes", type=int, default=300)
    parser.add_argument("--k_counterfactuals", type=int, default=4)
    parser.add_argument("--max_new_tokens", type=int, default=128)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--device", type=str, default="cuda:0")
    parser.add_argument("--rank", type=int, default=0)
    parser.add_argument("--world_size", type=int, default=1)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO if args.verbose else logging.WARNING)

    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    logger.info("Ensuring nuScenes metadata tables are local (%s, %s)", args.nuscenes_path, args.nuscenes_version)
    ensure_metadata_tables(args.nuscenes_path, args.nuscenes_version, args.nuscenes_s3_bucket, args.nuscenes_s3_prefix)
    ensure_maps(args.nuscenes_path, args.nuscenes_version, args.nuscenes_s3_bucket, args.nuscenes_s3_prefix)

    logger.info("Loading nuScenes (%s, %s)", args.nuscenes_path, args.nuscenes_version)
    nusc = NuScenes(version=args.nuscenes_version, dataroot=args.nuscenes_path, verbose=args.verbose)

    logger.info("Loading Qwen2.5-VL-72B labeler from %s", args.vlm_model_path)
    cot_config: Dict[str, Any] = {"pretrained_model_path": args.vlm_model_path}
    if torch.cuda.device_count() > 1:
        # Reserve headroom on the GPU that must ALSO hold the SFT model and
        # both models' generation transients: accelerate's balanced auto-split
        # of the ~137GiB fp16 72B across 2x A100-80GB otherwise leaves cuda:0
        # only ~10GiB free -- too tight once the SFT model (+KV/vision
        # activations) lands there. Capping GPU0 pushes ~7GiB of 72B layers
        # onto the other GPU(s), whose caps still leave room for their share
        # of generation KV.
        gib = 1024 ** 3
        max_memory = {
            i: torch.cuda.get_device_properties(i).total_memory - int(1.5 * gib)
            for i in range(torch.cuda.device_count())
        }
        max_memory[0] = torch.cuda.get_device_properties(0).total_memory - 18 * gib
        cot_config["max_memory"] = max_memory
    cot_model = CoTAnnotationModel(cot_config)

    logger.info("Loading AutoVLA SFT checkpoint via %s", args.sft_config)
    sft_model, sft_processor = load_sft_model(args.sft_config, args.device, args.sft_checkpoint_override)
    autovla = sft_model.autovla

    n_written, n_skipped = 0, 0
    for scene in iter_pilot_scenes(
        nusc, args.num_scenes, args.rank, args.world_size,
        args.nuscenes_path, args.nuscenes_s3_bucket, args.nuscenes_s3_prefix,
    ):
        out_path = outdir / f"{scene['token']}.json"
        if out_path.exists():
            # A preemption can truncate a non-atomically-written file from an
            # OLD run of this script (writes are atomic below, but stale rank
            # dirs may predate that) -- validate before trusting the skip,
            # since run.py uploads every *.json here to the training corpus.
            try:
                with open(out_path) as f:
                    json.load(f)
                continue
            except (json.JSONDecodeError, OSError):
                logger.warning("Regenerating %s: existing file is truncated/corrupt", out_path)
                out_path.unlink()

        try:
            gt_lateral, gt_longitudinal = parse_gt_hint(scene["gt_meta_action"])
        except ValueError as e:
            logger.warning("Skipping %s: %s", scene["token"], e)
            n_skipped += 1
            continue
        gt_hint = f"{gt_lateral} with {gt_longitudinal}" if gt_longitudinal != "stop" else "stop"

        real_inputs = build_cot_generation_inputs(cot_model.processor, scene, gt_hint)
        real_cot = cot_model.vlm_inference(real_inputs)[0].strip()

        alt_hints = build_alternative_hints(gt_lateral, gt_longitudinal, args.k_counterfactuals)

        input_features = build_input_features(scene)
        prompt_inputs = autovla.get_prompt(input_features)
        prompt_model_inputs = _to_device(prompt_inputs, args.device)

        counterfactuals = []
        for cf_id, alt_hint in enumerate(alt_hints):
            cf_inputs = build_cot_generation_inputs(cot_model.processor, scene, alt_hint)
            cf_cot = cot_model.vlm_inference(cf_inputs)[0].strip()

            cf_trajectory = continue_from_text(
                autovla, prompt_model_inputs, cf_cot, args.max_new_tokens, args.seed + cf_id + 1,
            )
            counterfactuals.append({
                "cf_id": cf_id,
                "action_hint": alt_hint,
                "cot_output": cf_cot,
                "trajectory": cf_trajectory.tolist() if cf_trajectory is not None else None,
                "trajectory_failed": cf_trajectory is None,
            })

        result = dict(scene)
        result["cot_output"] = real_cot
        result["counterfactuals"] = counterfactuals
        # Atomic write (same rationale as boto3's download temp+rename): on
        # this preemptible job a SIGKILL mid-dump must not leave a truncated
        # .json that the resume skip would keep and run.py would upload. The
        # .tmp suffix also keeps it out of run.py's *.json upload glob.
        tmp_path = out_path.with_name(out_path.name + ".tmp")
        with open(tmp_path, "w") as f:
            json.dump(result, f, indent=2)
        os.replace(tmp_path, out_path)
        n_written += 1

        if args.verbose:
            n_failed = sum(1 for c in counterfactuals if c["trajectory_failed"])
            logger.info("[%d] %s: %d/%d counterfactual trajectories ok",
                        n_written, scene["token"], len(counterfactuals) - n_failed, len(counterfactuals))

    logger.info("Done: %d scenes written, %d skipped, output=%s", n_written, n_skipped, outdir)


if __name__ == "__main__":
    main()
